global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'catalog-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['catalog-service:5000']

  - job_name: 'order-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['order-service:5001']

  - job_name: 'payment-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['payment-service:5002']
